# Site settings
# These are used to personalize your new site.
title: Riley W. Osborne
logo: "/images/portfolio_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science with a Mathematics Minor (class of 2025)
  <br /><br />
  <a href="https://app.joinhandshake.com/stu/users/33316167">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/riley-osborne-142381303/">View My LinkedIn Profile</a>
repository: "RileyOsborne26/RileyOsborne26.github.io"
github_username:  RileyOsborne26 # update with your username
google_analytics: G-CSSR62CEMM # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

